apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::959394354712:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-MDFOWFJCLIDV
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::959394354712:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-04T18:04:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1598"
  uid: c8632964-6cd4-4f45-9505-a8a80de79203
